import type {
  Building,
  Unit,
  Tenant,
  Booking,
  PublicCharge,
  RegulationRun,
  RegulationUnitSetting,
  RegulationBookingSetting,
} from './models';

// Simple seeded example data for the prototype

export const buildings: Building[] = [
  {
    id: 'b1',
    name: 'Nørrebro Residences',
    address: 'Nørrebrogade 10, 2200 København N',
    unitIds: [
      'u1',
      'u2',
      'u3',
      'u4',
      'u5',
      'u6',
      'u7',
      'u8',
      'u9',
      'u10',
      'u11',
      'u12',
      'u13',
      'u14',
      'u15',
      'u16',
      'u17',
      'u18',
      'u19',
      'u20',
      'u21',
      'u22',
      'u23',
      'u24',
      'u25',
      'u26',
      'u27',
      'u28',
      'u29',
      'u30',
      'u31',
      'u32',
      'u33',
      'u34',
    ],
  },
];

export const units: Unit[] = [
  {
    id: 'u1',
    buildingId: 'b1',
    name: '1. th.',
    areaSqm: 65,
    baseMonthlyRent: 8000,
    unitType: 'apartment',
  },
  {
    id: 'u2',
    buildingId: 'b1',
    name: '1. tv.',
    areaSqm: 80,
    baseMonthlyRent: 9500,
    unitType: 'apartment',
  },
  {
    id: 'u3',
    buildingId: 'b1',
    name: '2. th.',
    areaSqm: 55,
    baseMonthlyRent: 7200,
    unitType: 'apartment',
  },
  {
    id: 'u4',
    buildingId: 'b1',
    name: 'St. th. (erhverv)',
    areaSqm: 120,
    baseMonthlyRent: 15000,
    unitType: 'commercial',
  },
  {
    id: 'u5',
    buildingId: 'b1',
    name: '2. tv.',
    areaSqm: 70,
    baseMonthlyRent: 8200,
    unitType: 'shared',
  },
  {
    id: 'u6',
    buildingId: 'b1',
    name: '2. mf.',
    areaSqm: 68,
    baseMonthlyRent: 8100,
    unitType: 'shared',
  },
  {
    id: 'u7',
    buildingId: 'b1',
    name: '3. th.',
    areaSqm: 62,
    baseMonthlyRent: 7800,
    unitType: 'apartment',
  },
  {
    id: 'u8',
    buildingId: 'b1',
    name: '3. tv.',
    areaSqm: 75,
    baseMonthlyRent: 9000,
    unitType: 'apartment',
  },
  {
    id: 'u9',
    buildingId: 'b1',
    name: '3. mf.',
    areaSqm: 58,
    baseMonthlyRent: 7600,
    unitType: 'apartment',
  },
  {
    id: 'u10',
    buildingId: 'b1',
    name: 'St. tv. (erhverv)',
    areaSqm: 140,
    baseMonthlyRent: 18500,
    unitType: 'commercial',
  },
  {
    id: 'u11',
    buildingId: 'b1',
    name: '4. th.',
    areaSqm: 66,
    baseMonthlyRent: 8300,
    unitType: 'apartment',
  },
  {
    id: 'u12',
    buildingId: 'b1',
    name: '4. tv.',
    areaSqm: 72,
    baseMonthlyRent: 9100,
    unitType: 'apartment',
  },
  {
    id: 'u13',
    buildingId: 'b1',
    name: '4. mf.',
    areaSqm: 60,
    baseMonthlyRent: 7900,
    unitType: 'shared',
  },
  {
    id: 'u14',
    buildingId: 'b1',
    name: '5. th.',
    areaSqm: 63,
    baseMonthlyRent: 8000,
    unitType: 'apartment',
  },
  {
    id: 'u15',
    buildingId: 'b1',
    name: '5. tv.',
    areaSqm: 78,
    baseMonthlyRent: 9400,
    unitType: 'apartment',
  },
  {
    id: 'u16',
    buildingId: 'b1',
    name: '5. mf.',
    areaSqm: 59,
    baseMonthlyRent: 7700,
    unitType: 'apartment',
  },
  {
    id: 'u17',
    buildingId: 'b1',
    name: '6. th.',
    areaSqm: 64,
    baseMonthlyRent: 8050,
    unitType: 'apartment',
  },
  {
    id: 'u18',
    buildingId: 'b1',
    name: '6. tv.',
    areaSqm: 74,
    baseMonthlyRent: 9300,
    unitType: 'apartment',
  },
  {
    id: 'u19',
    buildingId: 'b1',
    name: '6. mf.',
    areaSqm: 57,
    baseMonthlyRent: 7500,
    unitType: 'apartment',
  },
  {
    id: 'u20',
    buildingId: 'b1',
    name: 'Kælder 1 (erhverv)',
    areaSqm: 160,
    baseMonthlyRent: 19000,
    unitType: 'commercial',
  },
  {
    id: 'u21',
    buildingId: 'b1',
    name: '7. th.',
    areaSqm: 61,
    baseMonthlyRent: 7900,
    unitType: 'apartment',
  },
  {
    id: 'u22',
    buildingId: 'b1',
    name: '7. tv.',
    areaSqm: 73,
    baseMonthlyRent: 9200,
    unitType: 'apartment',
  },
  {
    id: 'u23',
    buildingId: 'b1',
    name: '7. mf.',
    areaSqm: 56,
    baseMonthlyRent: 7400,
    unitType: 'apartment',
  },
  {
    id: 'u24',
    buildingId: 'b1',
    name: '8. th.',
    areaSqm: 65,
    baseMonthlyRent: 8150,
    unitType: 'apartment',
  },
  {
    id: 'u25',
    buildingId: 'b1',
    name: '8. tv.',
    areaSqm: 79,
    baseMonthlyRent: 9500,
    unitType: 'apartment',
  },
  {
    id: 'u26',
    buildingId: 'b1',
    name: '8. mf.',
    areaSqm: 60,
    baseMonthlyRent: 7850,
    unitType: 'shared',
  },
  {
    id: 'u27',
    buildingId: 'b1',
    name: '9. th.',
    areaSqm: 62,
    baseMonthlyRent: 8000,
    unitType: 'apartment',
  },
  {
    id: 'u28',
    buildingId: 'b1',
    name: '9. tv.',
    areaSqm: 76,
    baseMonthlyRent: 9400,
    unitType: 'apartment',
  },
  {
    id: 'u29',
    buildingId: 'b1',
    name: '9. mf.',
    areaSqm: 58,
    baseMonthlyRent: 7650,
    unitType: 'apartment',
  },
  {
    id: 'u30',
    buildingId: 'b1',
    name: '10. th.',
    areaSqm: 63,
    baseMonthlyRent: 8100,
    unitType: 'apartment',
  },
  {
    id: 'u31',
    buildingId: 'b1',
    name: '10. tv.',
    areaSqm: 77,
    baseMonthlyRent: 9550,
    unitType: 'apartment',
  },
  {
    id: 'u32',
    buildingId: 'b1',
    name: '10. mf.',
    areaSqm: 59,
    baseMonthlyRent: 7800,
    unitType: 'apartment',
  },
  {
    id: 'u33',
    buildingId: 'b1',
    name: 'Loft 1',
    areaSqm: 45,
    baseMonthlyRent: 6500,
    unitType: 'shared',
  },
  {
    id: 'u34',
    buildingId: 'b1',
    name: 'Loft 2',
    areaSqm: 48,
    baseMonthlyRent: 6700,
    unitType: 'apartment',
  },
];

export const tenants: Tenant[] = [
  { id: 't1', name: 'Anna Jensen' },
  { id: 't2', name: 'Lars Pedersen' },
  { id: 't3', name: 'Mette Sørensen' },
  { id: 't4', name: 'Café Nørrelykke ApS' },
  { id: 't5', name: 'Jonas Kristensen' },
  { id: 't6', name: 'Sofie Holm' },
  { id: 't7', name: 'Nikolaj Hansen' },
  { id: 't8', name: 'Camilla Bruun' },
  { id: 't9', name: 'Rasmus Poulsen' },
  { id: 't10', name: 'København Yoga ApS' },
  { id: 't11', name: 'Ida Madsen' },
  { id: 't12', name: 'Peter Larsen' },
  { id: 't13', name: 'Maja Pedersen' },
  { id: 't14', name: 'Oliver Schmidt' },
  { id: 't15', name: 'Emma Nielsen' },
  { id: 't16', name: 'Frederik Rasmussen' },
  { id: 't17', name: 'Laura Andersen' },
  { id: 't18', name: 'Thomas Sørensen' },
  { id: 't19', name: 'Maria Jensen' },
  { id: 't20', name: 'Nordic Design Studio ApS' },
  { id: 't21', name: 'Daniel Olesen' },
  { id: 't22', name: 'Line Frederiksen' },
  { id: 't23', name: 'Sebastian Lund' },
  { id: 't24', name: 'Julie Andersen' },
  { id: 't25', name: 'Kasper Thomsen' },
  { id: 't26', name: 'Nanna Bjerregaard' },
  { id: 't27', name: 'Magnus Kjær' },
  { id: 't28', name: 'Clara Møller' },
  { id: 't29', name: 'Mikkel Kristoffersen' },
  { id: 't30', name: 'Amalie Vestergaard' },
  { id: 't31', name: 'Anders Nygaard' },
  { id: 't32', name: 'Signe Villadsen' },
  { id: 't33', name: 'Victor Broberg' },
  { id: 't34', name: 'Sara Leth' },
];

export const bookings: Booking[] = [
  {
    id: 'bk1',
    unitId: 'u1',
    tenantId: 't1',
    startDate: '2022-01-01',
    monthlyRent: 8000,
  },
  {
    id: 'bk2',
    unitId: 'u2',
    tenantId: 't2',
    startDate: '2023-03-01',
    monthlyRent: 9500,
  },
  {
    id: 'bk3',
    unitId: 'u3',
    tenantId: 't3',
    startDate: '2021-08-01',
    monthlyRent: 7200,
  },
  {
    id: 'bk4',
    unitId: 'u4',
    tenantId: 't4',
    startDate: '2020-05-01',
    monthlyRent: 15000,
  },
  // Leases that end during 2026
  {
    id: 'bk5',
    unitId: 'u5',
    tenantId: 't5',
    startDate: '2022-02-01',
    endDate: '2026-03-15',
    monthlyRent: 8200,
  },
  {
    id: 'bk6',
    unitId: 'u6',
    tenantId: 't6',
    startDate: '2021-11-01',
    endDate: '2026-10-31',
    monthlyRent: 8100,
  },
  {
    id: 'bk7',
    unitId: 'u7',
    tenantId: 't7',
    startDate: '2023-05-01',
    endDate: '2026-01-31',
    monthlyRent: 7800,
  },
  {
    id: 'bk8',
    unitId: 'u8',
    tenantId: 't8',
    startDate: '2022-09-01',
    endDate: '2026-06-30',
    monthlyRent: 9000,
  },
  {
    id: 'bk9',
    unitId: 'u9',
    tenantId: 't9',
    startDate: '2020-04-15',
    endDate: '2026-12-31',
    monthlyRent: 7600,
  },
  {
    id: 'bk10',
    unitId: 'u10',
    tenantId: 't10',
    startDate: '2019-01-01',
    endDate: '2026-05-31',
    monthlyRent: 18500,
  },
  // Leases that start during 2026
  {
    id: 'bk11',
    unitId: 'u11',
    tenantId: 't11',
    startDate: '2026-02-01',
    monthlyRent: 8300,
  },
  {
    id: 'bk12',
    unitId: 'u12',
    tenantId: 't12',
    startDate: '2026-07-01',
    monthlyRent: 9100,
  },
  {
    id: 'bk13',
    unitId: 'u13',
    tenantId: 't13',
    startDate: '2026-09-15',
    monthlyRent: 7900,
  },
  {
    id: 'bk14',
    unitId: 'u14',
    tenantId: 't14',
    startDate: '2026-01-10',
    monthlyRent: 8000,
  },
  {
    id: 'bk15',
    unitId: 'u15',
    tenantId: 't15',
    startDate: '2026-11-01',
    monthlyRent: 9400,
  },
  {
    id: 'bk16',
    unitId: 'u16',
    tenantId: 't16',
    startDate: '2026-03-20',
    monthlyRent: 7700,
  },
  // Long-running open-ended leases (no endDate)
  {
    id: 'bk17',
    unitId: 'u17',
    tenantId: 't17',
    startDate: '2021-06-01',
    monthlyRent: 8050,
  },
  {
    id: 'bk18',
    unitId: 'u18',
    tenantId: 't18',
    startDate: '2020-09-01',
    monthlyRent: 9300,
  },
  {
    id: 'bk19',
    unitId: 'u19',
    tenantId: 't19',
    startDate: '2022-01-15',
    monthlyRent: 7500,
  },
  {
    id: 'bk20',
    unitId: 'u20',
    tenantId: 't20',
    startDate: '2018-04-01',
    monthlyRent: 19000,
  },
  {
    id: 'bk21',
    unitId: 'u21',
    tenantId: 't21',
    startDate: '2023-08-01',
    monthlyRent: 7900,
  },
  {
    id: 'bk22',
    unitId: 'u22',
    tenantId: 't22',
    startDate: '2024-02-01',
    monthlyRent: 9200,
  },
  {
    id: 'bk23',
    unitId: 'u23',
    tenantId: 't23',
    startDate: '2024-10-01',
    monthlyRent: 7400,
  },
  {
    id: 'bk24',
    unitId: 'u24',
    tenantId: 't24',
    startDate: '2019-11-01',
    monthlyRent: 8150,
  },
  {
    id: 'bk25',
    unitId: 'u25',
    tenantId: 't25',
    startDate: '2022-05-01',
    monthlyRent: 9500,
  },
  {
    id: 'bk26',
    unitId: 'u26',
    tenantId: 't26',
    startDate: '2023-03-01',
    monthlyRent: 7850,
  },
  {
    id: 'bk27',
    unitId: 'u27',
    tenantId: 't27',
    startDate: '2021-09-01',
    monthlyRent: 8000,
  },
  {
    id: 'bk28',
    unitId: 'u28',
    tenantId: 't28',
    startDate: '2020-06-01',
    monthlyRent: 9400,
  },
  {
    id: 'bk29',
    unitId: 'u29',
    tenantId: 't29',
    startDate: '2022-12-01',
    monthlyRent: 7650,
  },
  {
    id: 'bk30',
    unitId: 'u30',
    tenantId: 't30',
    startDate: '2021-01-15',
    monthlyRent: 8100,
  },
  {
    id: 'bk31',
    unitId: 'u31',
    tenantId: 't31',
    startDate: '2019-03-01',
    monthlyRent: 9550,
  },
  {
    id: 'bk32',
    unitId: 'u32',
    tenantId: 't32',
    startDate: '2023-07-01',
    monthlyRent: 7800,
  },
  {
    id: 'bk33',
    unitId: 'u33',
    tenantId: 't33',
    startDate: '2024-01-01',
    monthlyRent: 6500,
  },
  {
    id: 'bk34',
    unitId: 'u34',
    tenantId: 't34',
    startDate: '2024-09-01',
    monthlyRent: 6700,
  },
];

// Example: seeded yearly expenses for 2025 (previous) and 2026 (new)
export const publicCharges: PublicCharge[] = [
  {
    id: 'pc1',
    buildingId: 'b1',
    label: 'Municipality taxes',
    sku: '1001',
    date: '2026-01-01',
    vat: 0,
    includeInCalculation: true,
    periodType: 'year',
    prevPeriodFrom: '2025-01-01',
    prevPeriodTo: '2025-12-31',
    prevAmount: 190790.49,
    nextPeriodFrom: '2026-01-01',
    nextPeriodTo: '2026-12-31',
    nextAmount: 209205.6,
  },
  {
    id: 'pc2',
    buildingId: 'b1',
    label: 'Renovationsafg. - Bolig var. OMK',
    sku: '1006',
    date: '2026-01-01',
    vat: 0,
    includeInCalculation: true,
    periodType: 'year',
    prevPeriodFrom: '2025-01-01',
    prevPeriodTo: '2025-12-31',
    prevAmount: 76481.93,
    nextPeriodFrom: '2026-01-01',
    nextPeriodTo: '2026-12-31',
    nextAmount: 120962.0,
  },
  {
    id: 'pc3',
    buildingId: 'b1',
    label: 'Rottebekæmpelse',
    sku: '1007',
    date: '2026-01-01',
    vat: 0,
    includeInCalculation: true,
    periodType: 'year',
    prevPeriodFrom: '2025-01-01',
    prevPeriodTo: '2025-12-31',
    prevAmount: 1095.33,
    nextPeriodFrom: '2026-01-01',
    nextPeriodTo: '2026-12-31',
    nextAmount: 2911.35,
  },
  {
    id: 'pc4',
    buildingId: 'b1',
    label: 'Elafgift m.m. - Bolig var. OMK',
    sku: '1004',
    date: '2026-01-01',
    vat: 0,
    includeInCalculation: true,
    periodType: 'year',
    prevPeriodFrom: '2025-01-01',
    prevPeriodTo: '2025-12-31',
    prevAmount: 53633.68,
    nextPeriodFrom: '2026-01-01',
    nextPeriodTo: '2026-12-31',
    nextAmount: 26293.59,
  },
];

const totalAreaSqm = units.reduce((sum, u) => sum + u.areaSqm, 0);

// Default regulation run used in the prototype (active run for editing)
const seededPrevTotal = publicCharges.reduce(
  (sum, c) => sum + c.prevAmount,
  0,
);
const seededNextTotal = publicCharges.reduce(
  (sum, c) => sum + c.nextAmount,
  0,
);

export const initialRegulationRun: RegulationRun = {
  id: 'rr1',
  buildingId: 'b1',
  publicChargeId: 'pc1',
  notificationDate: '2026-05-01',
  adjustmentStartDate: '2026-09-01',
  retroactiveEnabled: false,
  status: 'draft',
  totalPrevExpenses: seededPrevTotal,
  totalNextExpenses: seededNextTotal,
  totalDelta: seededNextTotal - seededPrevTotal,
  totalRentableAreaSqm: totalAreaSqm,
  adjustmentPerSqm: (seededNextTotal - seededPrevTotal) / totalAreaSqm,
};

// Regulation runs for display in Buildings screen (current + historical)
export const regulationRuns: RegulationRun[] = [
  initialRegulationRun,
  {
    id: 'rr2',
    buildingId: 'b1',
    publicChargeId: 'pc1',
    notificationDate: '2025-04-15',
    adjustmentStartDate: '2025-08-01',
    retroactiveEnabled: true,
    retroFrom: '2026-01-01',
    retroTo: '2026-08-31',
    status: 'approved',
    totalPrevExpenses: 220000,
    totalNextExpenses: 240000,
    totalDelta: 20000,
    totalRentableAreaSqm: totalAreaSqm,
    adjustmentPerSqm: 20000 / totalAreaSqm,
  },
  {
    id: 'rr3',
    buildingId: 'b1',
    publicChargeId: 'pc2',
    notificationDate: '2024-03-20',
    adjustmentStartDate: '2024-07-01',
    retroactiveEnabled: false,
    status: 'approved',
    totalPrevExpenses: 200000,
    totalNextExpenses: 220000,
    totalDelta: 20000,
    totalRentableAreaSqm: totalAreaSqm,
    adjustmentPerSqm: 20000 / totalAreaSqm,
  },
];

export const initialRegulationUnitSettings: RegulationUnitSetting[] = [
  ...units.map((u) => ({
    regulationRunId: initialRegulationRun.id,
    unitId: u.id,
    excludeFromCalculation: false,
  })),
  ...units.map((u) => ({
    regulationRunId: 'rr2',
    unitId: u.id,
    excludeFromCalculation: false,
  })),
  ...units.map((u) => ({
    regulationRunId: 'rr3',
    unitId: u.id,
    excludeFromCalculation: false,
  })),
];

export const initialRegulationBookingSettings: RegulationBookingSetting[] =
  bookings.map((b) => ({
    regulationRunId: initialRegulationRun.id,
    bookingId: b.id,
    excludeFromApplication: false,
  }));

